version: '3'
services:
  db:
    image: mysql:latest
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
      MYSQL_USER: root
    volumes:
          - ./src/mysql:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
  nginx:
    image: nginx:1.13
    environment:
      APP_NAME: app
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./www:/var/www/
      - ./src/nginx:/usr/share/nginx/html
      - ./src/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./src/nginx/logs:/var/log/nginx/
  app:
    build: ./src/app
    volumes:
        - ./www:/var/www
